@Gateway_HostAddress = https://gateway.victoriousocean-546beaa5.westeurope.azurecontainerapps.io

POST {{Gateway_HostAddress}}/api/users/login
Accept: application/json

{
    "email": "user@example.com",
    "password": "password123"
}

###
