@SkillService_HostAddress = http://localhost:5111


Get {{SkillService_HostAddress}}/skills
Accept: application/json

###
Post {{SkillService_HostAddress}}/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDljOTFkNy05N2VjLTQwNGQtODQ3Ny1jMDhmZDY4YTRjNTMiLCJnaXZlbl9uYW1lIjoiRGF2aWQiLCJmYW1pbHlfbmFtZSI6IkFyYW1pcyIsImp0aSI6IjZmMzcxMzc5LTQyNGEtNDQwZS1hZGU5LTlmY2JmMWNmZDliYSIsImV4cCI6MTc0MTEzNDYwMSwiaXNzIjoiU2tpbGxTd2FwSXNzdWVyIiwiYXVkIjoiU2tpbGxTd2FwQXVkaWVuY2UifQ.vHwSbD1UTXxJ-e35_KYCfE7Jvj455_Y5FY4S_0VCPNw

{
    "name": "Name",
    "description": "Beschreibung",
    "isOffering": false
}
###
