using Microsoft.Extensions.Logging;
using CQRS.Handlers;
using CQRS.Models;
using NotificationService.Application.Commands;
using NotificationService.Domain.ResponseModels;
using NotificationService.Domain.Repositories;
using NotificationService.Domain.Services;
using Core.Common.Exceptions;
using System.Text.Json;

namespace NotificationService.Application.CommandHandlers;

public class PreviewTemplateCommandHandler(
    INotificationUnitOfWork unitOfWork,
    ITemplateEngine templateEngine,
    ILogger<PreviewTemplateCommandHandler> logger)
    : BaseCommandHandler<PreviewTemplateCommand, TemplatePreviewResponse>(logger)
{
    private readonly INotificationUnitOfWork _unitOfWork = unitOfWork;
    private readonly ITemplateEngine _templateEngine = templateEngine;

    public override async Task<ApiResponse<TemplatePreviewResponse>> Handle(
        PreviewTemplateCommand request,
        CancellationToken cancellationToken)
    {
        try
        {
            var template = await _unitOfWork.EmailTemplates
                .GetByIdAsync(request.TemplateId, cancellationToken);

            if (template == null)
            {
                return Error("Template not found", ErrorCodes.ResourceNotFound);
            }

            // Get variables - use provided or generate sample data from schema
            var variables = request.Variables ?? GenerateSampleVariables(template.VariablesSchema);

            // Render the template
            var renderedSubject = _templateEngine.RenderTemplate(template.Subject, variables);
            var renderedHtml = _templateEngine.RenderTemplate(template.HtmlContent, variables);
            var renderedText = _templateEngine.RenderTemplate(template.TextContent, variables);

            // Check for missing variables (variables in template but not provided)
            var missingVariables = FindMissingVariables(template.Subject + template.HtmlContent, variables);

            var response = new TemplatePreviewResponse
            {
                Subject = renderedSubject,
                HtmlContent = renderedHtml,
                TextContent = renderedText,
                MissingVariables = missingVariables,
                IsValid = missingVariables.Count == 0,
                ValidationErrors = missingVariables.Count > 0
                    ? new List<string> { $"Missing variables: {string.Join(", ", missingVariables)}" }
                    : new List<string>()
            };

            Logger.LogInformation("Template {TemplateId} preview generated by user {UserId}",
                request.TemplateId, request.UserId);

            return Success(response);
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error generating preview for template {TemplateId}", request.TemplateId);
            return Error("An error occurred while generating the template preview", ErrorCodes.InternalError);
        }
    }

    private Dictionary<string, string> GenerateSampleVariables(string? variablesSchema)
    {
        var sampleData = new Dictionary<string, string>();

        if (string.IsNullOrEmpty(variablesSchema))
        {
            return sampleData;
        }

        try
        {
            var schema = JsonSerializer.Deserialize<Dictionary<string, string>>(variablesSchema);
            if (schema == null) return sampleData;

            foreach (var kvp in schema)
            {
                sampleData[kvp.Key] = kvp.Value switch
                {
                    "string" => GetSampleStringValue(kvp.Key),
                    "number" => "30",
                    _ => $"[{kvp.Key}]"
                };
            }
        }
        catch (JsonException)
        {
            Logger.LogWarning("Could not parse variables schema: {Schema}", variablesSchema);
        }

        return sampleData;
    }

    private static string GetSampleStringValue(string key)
    {
        return key.ToLowerInvariant() switch
        {
            "firstname" or "recipientfirstname" => "Max",
            "lastname" or "recipientlastname" => "Mustermann",
            "partnername" or "rescheduledbyname" => "Lisa Schmidt",
            "skillname" => "C# Programming",
            "email" or "recipientemail" => "max.mustermann@example.com",
            "verificationurl" or "reseturl" => "https://skillswap.app/verify/abc123",
            "appurl" => "https://skillswap.app",
            "meetinglink" => "https://skillswap.app/meeting/xyz789",
            "scheduleddate" or "oldscheduleddate" or "newscheduleddate" => "15. Januar 2025",
            "scheduledtime" or "oldscheduledtime" or "newscheduledtime" => "14:00 Uhr",
            "reason" => "Terminkonflikt",
            _ => $"[{key}]"
        };
    }

    private static List<string> FindMissingVariables(string template, Dictionary<string, string> variables)
    {
        var missing = new List<string>();

        // Find all {{variable}} patterns in the template
        var regex = new System.Text.RegularExpressions.Regex(@"\{\{(\w+)\}\}");
        var matches = regex.Matches(template);

        foreach (System.Text.RegularExpressions.Match match in matches)
        {
            var varName = match.Groups[1].Value;
            if (!variables.ContainsKey(varName))
            {
                if (!missing.Contains(varName))
                {
                    missing.Add(varName);
                }
            }
        }

        return missing;
    }
}
